import type { NextPage } from "next";
import Head from "next/head";
import Navigation from '../components/Navigation'



const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Blinq • Integrations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <Navigation />
      </main>

    </div>
  );
};

export default Home;
