import type { NextPage } from "next";
import Head from "next/head";
import Navigation from '../components/Navigation'
import { useAuth } from "../context/AuthContext";
import IntegrationsDashboard from '../components/IntegrationsDashboard'



const Home: NextPage = () => {
  const { currentUser } = useAuth()

  return (
    <div>

      <Head>
        <title>Blinq • Integrations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {currentUser ? <IntegrationsDashboard /> : 'Not logged In'}
    </div>
  );
};

export default Home;
